### PR TITLE
Prep 0.7.2 release

### PR DESCRIPTION
**Pull request by ableuler**

### CODE REVIEW

**Comment by rokroskar** [comment]
This should have been 0.8.0 I guess...?

**Comment by ableuler** [comment]
> This should have been 0.8.0 I guess...?

On the notebooks-service the introduced changes _should_ actually be backwards-compatible (I admit that we haven't tested this aspect very thoroughly). That's why I went for `0.7.2`.

**Comment by rokroskar** [comment]
sure but it's (much) more than a bugfix.

**Comment by ableuler** [comment]
yes, but we have been doing this all the time, no? I thought before 1.0.0 we were following [this logic](https://github.com/dbrock/semver-howto#alpha-and-beta-0xy), but we can also agree to increase the second digit for new features.

**Pull request merged**
