### PR TITLE
fix: accept zero as max_lines parameter for logs

### PR DESCRIPTION
**Pull request by olevski**
/deploy #persist

### CODE REVIEW

**Comment by ciyer** [comment]
This change makes sense, but it does't fix the problem that we were having. The backend still responds with this error when we try to make a query with `max_lines=0`:

```
{"error": {"code": 1422, "message": "The request was well-formed but was unable to be followed due to semantic errors.", "detail": null}}
```

**Comment by olevski** [comment]
> This change makes sense, but it does't fix the problem that we were having. The backend still responds with this error when we try to make a query with `max_lines=0`:
> 
> ```
> {"error": {"code": 1422, "message": "The request was well-formed but was unable to be followed due to semantic errors.", "detail": null}}
> ```

@ciyer there were actually 2 places where this needs to be changed. The first one I chaged is only for documentation purposes in the swagger page. Now it should truly work.

**Comment by ciyer** [comment]
Yes, this fixes the problem, thanks!

**Review by ciyer — APPROVED** [review]
👍

**Pull request merged**
