### PR TITLE
prep 0.8.11 release

### PR DESCRIPTION
**Pull request by olevski**

### CODE REVIEW

**Review by pameladelgado — COMMENTED** [review]
Would you also bump the chart version?

**Review by ableuler — APPROVED** [review]
Thanks!

**Review by pameladelgado — CHANGES_REQUESTED** [review]
Thanks!
I would disable the user session persistent volumes in the release for the moment until we have a cleanup mechanism in place.

**Review by pameladelgado — APPROVED** [review]
sorry, I meant to approve :smile:

**Comment by rokroskar** [comment]
@pameladelgado they are disabled by default: https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/helm-chart/renku-notebooks/values.yaml#L12-L15

**Pull request merged**
