### PR TITLE
feat: add requested resources info to servers endpoint

### LINKED ISSUE #223: feat: add resource information to pod annotations
It should be easy to add a couple of extra annotations to the pods about the environment resources/options selected during the start phase. These could be added to the `/servers` endpoint and be used by the UI to give extra information (e.g. number of GPU available)

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
Add the requested resources info to the `GET /servers` API response. This is an example, the new part is in the attribute `resources`

```
{
  "servers": {
    "flights-tutorial-d991bad2": {
      "annotations": {
        [...]
      },
      "name": "flights-tutorial-d991bad2",
      "resources": {
        "cpu": "0.1",
        "memory": "1073741824"
      },
      "started": "2020-03-12T16:54:30.000000Z",
      "state": {
        "pod_name": "jupyter-lorenzo-2ecavazzi-2etech-flights-2dtutorial-2dd991bad2"
      },
      "status": {
        [...]
      },
      "url": "https://lorenzo.dev.renku.ch/jupyterhub/user/lorenzo.cavazzi.tech/flights-tutorial-d991bad2/"
    }
  }
}
```

UPDATE: It's possible to test the change in `lorenzotest` deplyoment: https://lorenzotest.dev.renku.ch/

fix #223

### CODE REVIEW

**Comment by rokroskar** [comment]
Thanks @lorenzo-cavazzi! I'm wondering if it would make sense to show both resource request and limit? otoh it might make the most sense to _enforce_ both the memory and cpu requests as limits. At the moment, only the memory is enforced. Then we only need to show a single number, like you have done here.

**Comment by lorenzo-cavazzi** [comment]
We don't get any `cpu` value in the limits object if we don't enforce one. Currently, we only get the `memory` limit and it's always equal to the request counterpart.
On the other hand, do we *want* to enforce cpu limits? Is there any advantage? I see how allocating extra memory may be a problem when we need to reclaim that, but for the cpu I don't see the same problem

**Comment by rokroskar** [comment]
> We don't get any cpu value in the limits object if we don't enforce one

yes, that was my point - maybe we should. What can happen is that one user can starve a node of CPU. CPU is a compressible resource, meaning the OS can decide to throttle it or not. If you don't enforce CPU limits, a single greedy process can take over all of the CPU on the node adversely affecting all others.

**Comment by lorenzo-cavazzi** [comment]
I was going to look into enforcing the CPU limit since your argument is convincing. Should I open a different issue to keep track of that?

**Comment by rokroskar** [comment]
You just need to add the CPU limit to the pod in the spawner in the same way it's done for the memory. But maybe it warrants a discussion with the others - although the decision is either: a) we hope that the current way doesn't make too many people unhappy or b) we enforce it and then document the limitations

**Pull request merged**
