### PR TITLE
fix: use shortened commit-sha to check for an autosave match

### PR DESCRIPTION
**Pull request by mohammad-sdsc**
Fixes a bug in check for autosaved branch commit-sha where it was checking against the long commit-sha instead of the short one.

### CODE REVIEW

**Comment by mohammad-sdsc** [comment]
@rokroskar and @lorenzo-cavazzi please test this to see if you it resolves your issue. It worked for me.

**Comment by lorenzo-cavazzi** [comment]
It's testable in the UI form here: https://lorenzotest.dev.renku.ch
It's working for me, but there is the discussion going on here #187 and this PR is built on top of it, right? If it's not strictly related we can proceed and merge this

**Comment by mohammad-sdsc** [comment]
Did you test with this latest commit: https://github.com/SwissDataScienceCenter/renku-notebooks/pull/190/commits/2720d1f2d3c23038e3953d58d27d92349ff0f051?

**Comment by lorenzo-cavazzi** [comment]
right, let me update the preview and test it again

**Comment by mohammad-sdsc** [comment]
Please don't merge this until we agree upon the final solution in https://github.com/SwissDataScienceCenter/renku-notebooks/issues/187.

**Comment by rokroskar** [comment]
@mohammad-sdsc if this meets the requirements we came up with last Friday, could we merge it?

**Comment by mohammad-sdsc** [comment]
Done!

**Comment by mohammad-sdsc** [comment]
Closes https://github.com/SwissDataScienceCenter/renku-notebooks/issues/187

**Pull request merged**
