### PR TITLE
chore: use pre-commit hooks for chartpress --reset

### PR DESCRIPTION
**Pull request by rokroskar**
Add support for running `chartpress --reset` as a git pre-commit hook using the [`pre-commit`](https://pre-commit.com) package. 

To try it out: 

```bash
pipenv install --deploy 
pipenv run pre-commit install
pipenv run pre-commit run chartpress
```

Trying to commit a modified chart value that is handled by `chartpress` results in

```bash
git commit -am 'commiting woop'
black................................................(no files to check)Skipped
Flake8...............................................(no files to check)Skipped
chartpress reset.........................................................Failed
hookid: chartpress

Files were modified by this hook. Additional output:

$> git log -n 1 --pretty=format:%h -- . . jupyterhub singleuser
$> git log -n 1 --pretty=format:%h -- . chartpress.yaml
$> git log -n 1 --pretty=format:%h -- jupyterhub jupyterhub chartpress.yaml
$> git log -n 1 --pretty=format:%h -- git-clone git-clone chartpress.yaml
Updating helm-chart/renku-notebooks/values.yaml: image: {'repository': 'renku/renku-notebooks', 'tag': 'latest'}
Updating helm-chart/renku-notebooks/values.yaml: jupyterhub.hub.image: {'repository': 'renku/jupyterhub-k8s', 'tag': 'latest'}
Updating helm-chart/renku-notebooks/values.yaml: git_clone.image: {'repository': 'renku/git-clone', 'tag': 'latest'}
```

### CODE REVIEW

**Comment by mohammad-sdsc** [comment]
As far as I understood, this prevents unintentional modifications to the `Chart.yaml` and `values.yaml` files. If so, then it LGTM. One point though is what if we want to make changes to these files?
Also, `pre-commit` uses `python3.7` which I don't have on my machine. I tried with `python3` but then `black` complains. I had to change `.pre-commit-config.yaml` to use `python3.6`. This works but is a bit inconvenient and it would be good if there is a solution to that.

**Comment by rokroskar** [comment]
Aha thanks, I wasn't aware of the python version issue. I'll dig a bit in the docs. 

> One point though is what if we want to make changes to these files?

`chartpress` will only modify the `image` object of the parts of the chart that it controls (and the `version` in `Chart.yaml`). So in this case it's `jupyterhub.image`, `git-clone.image` and `image` (for the notebooks service itself). All the other parts of these files should remain unmodified and unaffected.

**Comment by rokroskar** [comment]
@mohammad-sdsc sorry I haven't had a chance to look into the python version problem - did you solve it?

**Comment by mohammad-sdsc** [comment]
Not really, I change the version to `3.6` on my system and revert it back later. It makes more sense to set it at `3.6` because that's the minimum version requirement for renku.

**Comment by rokroskar** [comment]
Oh now I see it - I didn't realize that was the requirement set for `black`. I'm pretty sure it doesn't need to be that way. I just pushed a change that removes that line,

**Comment by mohammad-sdsc** [comment]
This does not work on my system (Debian Linux) and gives me this error:
```
[INFO] Installing environment for https://github.com/ambv/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/home/mohammad/.cache/pre-commit/repo3x91u4nj/py_env-python3/bin/python3', '/home/mohammad/.cache/pre-commit/repo3x91u4nj/py_env-python3/bin/pip', 'install', '.')
Return code: 1
Expected return code: 0
Output:
    Processing /home/mohammad/.cache/pre-commit/repo3x91u4nj
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'error'

Errors:
      ERROR: Complete output from command /home/mohammad/.cache/pre-commit/repo3x91u4nj/py_env-python3/bin/python3 /home/mohammad/.cache/pre-commit/repo3x91u4nj/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp4oh3d__3:
      ERROR: Traceback (most recent call last):
        File "/home/mohammad/.cache/pre-commit/repo3x91u4nj/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
          main()
        File "/home/mohammad/.cache/pre-commit/repo3x91u4nj/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/mohammad/.cache/pre-commit/repo3x91u4nj/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-6c1m3az6/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 145, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-6c1m3az6/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 126, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-6c1m3az6/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 234, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-6c1m3az6/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 141, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 7, in <module>
          assert sys.version_info >= (3, 6, 0), "black requires Python 3.6+"
      AssertionError: black requires Python 3.6+
      ----------------------------------------
    ERROR: Command "/home/mohammad/.cache/pre-commit/repo3x91u4nj/py_env-python3/bin/python3 /home/mohammad/.cache/pre-commit/repo3x91u4nj/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp4oh3d__3" failed with error code 1 in /tmp/pip-req-build-ocdf7opo
```

My system's Python version is `3.5` but on `pipenv` it's `3.6`.

BTW, this was working when the `python 3.6` line was there.

**Comment by rokroskar** [comment]
ok I see - so we need the `language_version: python3.6` in there.

**Comment by rokroskar** [comment]
Or maybe just `python3`?

**Comment by mohammad-sdsc** [comment]
`python3` won't work either and gives the same error message.

**Comment by mohammad-sdsc** [comment]
Feel free to merge this!

**Pull request merged**
