### PR TITLE
jh: do not force lowercase

### LINKED ISSUE #45: Project with upper case is not started properly
The mounted volume (empty for) does not respect case at the moment. It results in a lab instance which cannot be used

Edit: This happens when converting existing projects to Renku (and not when creating them through the UI).

### PR DESCRIPTION
**Pull request by rokroskar**
closes #45

### CODE REVIEW

**Comment by rokroskar** [comment]
@leafty could be that the `self.name` has an uppercase in it -- let me check

**Comment by rokroskar** [comment]
I tried with a capitalized namespace and capitalized project -- seems ok.

**Comment by rokroskar** [comment]
I know what you mean - all the other variables are escaped in that piece of code except for self.name - but it looks like that must be escaped somewhere else.

**Comment by leafty** [comment]
Grrr! I asked you if it was safe:
```
Pod \"jupyter-johann-2Et-johann-2et-newnew-a342109\" is invalid: [metadata.name: Invalid value: \"jupyter-johann-2Et-johann-2et-newnew-a342109\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
```

**Comment by rokroskar** [comment]
that's not good

**Pull request merged**
