### PR TITLE
feat(app): detailed status messages

### LINKED ISSUE #1135: Update session status to include containers numbers and the steps's status when starting a session
Provide the following information about the session status when it is starting up.

```
{
   "status":{
      "state":"starting",
      "totalNumContainers":7,
      "readyNumContainers":3,
      "details":[
         {
            "step":"Setting up support containers",
            "status":"done"
         },
         {
            "step":"Cloning and configuring the repository",
            "status":"executing"
         },
         {
            "step":"Pulling main image",
            "status":"queued"
         },
         {
            "step":"Starting server",
            "status":"queued"
         }
      ]
   }
}

```

Status for steps:
done: step successfully completed
queued: queued for processing
executing: step in progress
failed: step completed with error

### PR DESCRIPTION
**Pull request by olevski**
closes #1135 

Provides more detailed information about server status.

Example status section of server response:
```json
                         "status": {
				"details": [{  # NEW
					"status": "ready",
					"step": "Initialization"
				}, {
					"status": "ready",
					"step": "Downloading session image"
				}, {
					"status": "executing",
					"step": "Cloning and configuring the repository"
				}, {
					"status": "waiting",
					"step": "Git credentials services"
				}, {
					"status": "waiting",
					"step": "Authentication and proxying services"
				}, {
					"status": "waiting",
					"step": "Auxiliary session services"
				}, {
					"status": "waiting",
					"step": "Starting session"
				}],
				"message": "Containers with non-ready statuses: git-proxy, git-sidecar, jupyter-server, oauth2-proxy.",
				"readyNumContainers": 2,  # NEW
				"state": "starting",
				"totalNumContainers": 7  # NEW
			},
```

Possible step states:
- ready
- executing
- waiting
- failed

Because of how containers react in k8s I modified the terminology a little bit. A container can be ready if it completes with 0 exit code or if it run and it passes all its probes. When all containers (i.e. steps) are ready then the whole session is ready. But the definitive flag on when the session can be accessed and is 100% ready is the `status.state` value. The `status.state` value will even check if the URL is reachable before turning to "running".

/deploy #persist

### CODE REVIEW

**Comment by olevski** [comment]
@ciyer @andre-code You can test against the CI deployment. Let me know what you think.

**Comment by olevski** [comment]
This is a draft because I want to make sure any changes from the ui side are addressed before someone reviews.

**Comment by andre-code** [comment]
> @ciyer @andre-code You can test against the CI deployment. Let me know what you think.

Thanks for this implementation, it works very well 👏, here you can find the UI implementation using this new information. 
https://github.com/SwissDataScienceCenter/renku-ui/pull/2054

**Review by mohammad-sdsc — APPROVED** [review]
LGTM.

**Pull request merged**
