### PR TITLE
fix typo in git command

### PR DESCRIPTION
**Pull request by rokroskar**
never merge before staging. 🤦‍♂️

### CODE REVIEW

**Comment by rokroskar** [comment]
No but I tested it locally 👍

**Comment by leafty** [comment]
@rokroskar I'm fine with force-merging since the build errors due to canonical repo being offline.

**Comment by rokroskar** [comment]
ugh -- these image builds really need to go into their own repo

**Comment by rokroskar** [comment]
alright, I'm doing a new project for the jupyter image builds, will rebase this PR on top of it

**Comment by leafty** [comment]
haha yeah good idea
> The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by rokroskar** [comment]
alright, build passes :)

**Comment by leafty** [comment]
Darn, it's just 4 minutes now

**Pull request merged**
