### PR TITLE
Add rancher API endpoint parameter

### PR DESCRIPTION
**Pull request by pameladelgado**
/deploy

### CODE REVIEW

**Comment by olevski** [comment]
@pameladelgado this is failing because it cannot be deployed because of missing permissions in rancher:
```
Error: query: failed to query with labels: secrets is forbidden: User "u-6rzj4" cannot list resource "secrets" in API group "" in the namespace "renku-ci-nb-704"
```

**Comment by pameladelgado** [comment]
> @pameladelgado this is failing because it cannot be deployed because of missing permissions in rancher:
> 
> ```
> Error: query: failed to query with labels: secrets is forbidden: User "u-6rzj4" cannot list resource "secrets" in API group "" in the namespace "renku-ci-nb-704"
> ```

@olevski Is not because of missing permissions, it's because renkubot couldnt create the namespace, since we needed to merge https://github.com/SwissDataScienceCenter/renku-actions/pull/2
Now it should work.dont strictly need to use the new version for all of the actions but I think is better for keeping consistency.
We

**Review by olevski — APPROVED** [review]
Contingent on the tests passing, I am ok with this.

**Comment by olevski** [comment]
@pameladelgado the problem is that the secret `RANCHER_DEV_API_ENDPOINT` that is needed for this to work is not in this repo's secrets or the org level secrets.

**Comment by pameladelgado** [comment]
> @pameladelgado the problem is that the secret `RANCHER_DEV_API_ENDPOINT` that is needed for this to work is not in this repo's secrets or the org level secrets.

Yes, this is fixed now. Deployment worked fine.

**Review by olevski — APPROVED** [review]

**Pull request merged**
